package com.skcoe.db.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserAccount generated by hbm2java
 */
@Entity
@Table(name="user_account",catalog="adm")
public class UserAccount  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -2968470171706921419L;

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("UserAccount [personid=");
		builder.append(personid);
		builder.append(", username=");
		builder.append(username);
		builder.append(", password=");
		builder.append(password);
		builder.append(", email=");
		builder.append(email);
		builder.append("]");
		return builder.toString();
	}

	private Integer personid;
     private String username;
     private String password;
     private String email;

    public UserAccount() {
    }

    public UserAccount(String username, String password, String email) {
       this.username = username;
       this.password = password;
       this.email = email;
    }
   
     @Id 
     @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name="personid", unique=true, nullable=false)
    public Integer getPersonid() {
        return this.personid;
    }
    
    public void setPersonid(Integer personid) {
        this.personid = personid;
    }

    
    @Column(name="username", length=35)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", length=32)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


