package com.skcoe.db.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Events generated by hbm2java
 */
@Entity
@Table(name="events"
    ,catalog="adm"
)
public class Events  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -3968519792454227055L;
	private long eventId;
     private Date eventDate;
     private String title;

    public Events() {
    }

	
    public Events(long eventId) {
        this.eventId = eventId;
    }
    public Events(long eventId, Date eventDate, String title) {
       this.eventId = eventId;
       this.eventDate = eventDate;
       this.title = title;
    }
   
     @Id 

    
    @Column(name="EVENT_ID", unique=true, nullable=false)
    public long getEventId() {
        return this.eventId;
    }
    
    public void setEventId(long eventId) {
        this.eventId = eventId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EVENT_DATE", length=19)
    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }

    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


